name: "Setup Vlang"
description: "Setup a Vlang environment downloading V and adding it to the PATH"
author: "vlang"
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  version:
    description: "Version to use. It can be the branch, tag or SHA to checkout from the V repository. Examples: 0.2.4, weekly.2022.07"
  version-file:
    description: "File containing the version to use. It can contain the branch, tag or SHA to checkout from the V repository. Examples: .v-version"
  check-latest:
    description: "Set this option if you want the action to check for the latest available version of V. If `stable` is false, it will check for the latest commit from the default branch."
    default: "false"
  stable:
    description: "Set this option if you want the action to use the stable version of V"
    default: "false"
  architecture:
    description: "Target architecture for V to use. Examples: linux, macos, windows. Will use system architecture by default."
outputs:
  bin-path:
    description: "Path to the directory that contains the V binary"
  v-bin-path:
    description: "Path to the V binary"
  version: 
    description: "Version of V installed"
  architecture:
    description: "Architecture that was used to install V"
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/index.js"
