name: CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: lib/

  test-action:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        scenario:
          - check-latest
          - stable
          - version
          - version-file
          - architecture
          - cache-false
          - clean-false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          name: build-output
          path: lib/

      - name: Run Action (check-latest)
        if: matrix.scenario == 'check-latest'
        uses: ./
        with:
          check-latest: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Action (stable)
        if: matrix.scenario == 'stable'
        uses: ./
        with:
          stable: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Action (version)
        if: matrix.scenario == 'version'
        uses: ./
        with:
          version: '0.5.1'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create version file
        if: matrix.scenario == 'version-file'
        shell: bash
        run: echo '0.5.1' > .v-version

      - name: Run Action (version-file)
        if: matrix.scenario == 'version-file'
        uses: ./
        with:
          version-file: '.v-version'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Action (architecture)
        if: matrix.scenario == 'architecture'
        uses: ./
        with:
          version: '0.5.1'
          architecture: 'x86_64'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Action (cache-false)
        if: matrix.scenario == 'cache-false'
        uses: ./
        with:
          version: '0.5.1'
          cache: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Action (clean-false)
        if: matrix.scenario == 'clean-false'
        uses: ./
        with:
          version: '0.5.1'
          clean: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test if the executable is available
        run: v version
